// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjJklOO3k1_Nsfd3P0BKmIgSpQc1WnlO4',
    appId: '1:1036230270482:web:0ed6990d0aad26b56d42cb',
    messagingSenderId: '1036230270482',
    projectId: 'blog-nest-3bedd',
    authDomain: 'blog-nest-3bedd.firebaseapp.com',
    storageBucket: 'blog-nest-3bedd.appspot.com',
    measurementId: 'G-65PJQJQGHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6q0nn4cygP8uk_7-lY1QIvweP15FOYZ4',
    appId: '1:1036230270482:android:c43dc8307f2bdbb46d42cb',
    messagingSenderId: '1036230270482',
    projectId: 'blog-nest-3bedd',
    storageBucket: 'blog-nest-3bedd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuvZTXMPqp7Du_xZmOz7mXC7TENZvq818',
    appId: '1:1036230270482:ios:4d4a66ff8226e47e6d42cb',
    messagingSenderId: '1036230270482',
    projectId: 'blog-nest-3bedd',
    storageBucket: 'blog-nest-3bedd.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDjJklOO3k1_Nsfd3P0BKmIgSpQc1WnlO4',
    appId: '1:1036230270482:web:bd9e84f6d05a3e616d42cb',
    messagingSenderId: '1036230270482',
    projectId: 'blog-nest-3bedd',
    authDomain: 'blog-nest-3bedd.firebaseapp.com',
    storageBucket: 'blog-nest-3bedd.appspot.com',
    measurementId: 'G-EES4J9GCQ0',
  );
}
